{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./bootloader.nix
    ./flatpak.nix
    ./intel-graphics.nix
    ./i18n.nix
    ./networking.nix
    ./nvidia.nix
    ./power-management.nix
    ./printing.nix
    ./qemu-guest.nix
    ./ssh.nix
    ./tailscale.nix
    ./time.nix
    ./wayland.nix
  ];
}
