{
  imports = [
    ./auto-cpufreq.nix
    ./carapace.nix
    ./claude-code.nix
    ./cli-common.nix
    ./datagrip.nix
    ./discord.nix
    ./docker.nix
    ./dotnet.nix
    ./fish.nix
    ./flatpak.nix
    ./fonts.nix
    ./global.nix
    ./go.nix
    ./gtk.nix
    ./helix.nix
    ./home-manager.nix
    ./java.nix
    ./jujutsu
    ./langs-common.nix
    ./aerospace
    ./macos
    ./dank-material-shell
    ./niri
    ./nushell.nix
    ./obsidian.nix
    ./opencode.nix
    ./rust
    ./skills
    ./starship.nix
    ./steam.nix
    ./tailscale.nix
    ./teams.nix
    ./wayland.nix
    ./webdev-common.nix
    ./wezterm
    ./wsl-bridge.nix
    ./zed.nix
    ./zellij.nix
    ./zsh.nix
    ./vlc.nix
    ./wallpaper-engine.nix
  ];
}
