{
  imports = [
    ./auto-cpufreq.nix
    ./carapace.nix
    ./cli-common.nix
    ./discord.nix
    ./docker.nix
    ./dotnet.nix
    ./fish.nix
    ./flatpak.nix
    ./fonts.nix
    ./global.nix
    ./helix.nix
    ./home-manager.nix
    ./java.nix
    ./jujutsu
    ./langs-common.nix
    ./nushell.nix
    ./obsidian.nix
    ./rust.nix
    ./starship.nix
    ./steam.nix
    ./wayland.nix
    ./webdev-common.nix
    ./wezterm
    ./wsl-bridge.nix
    ./zellij.nix
  ];
}
