# PLACEHOLDER — replace with the file generated by
# `nixos-generate-config --root /mnt` during install.
#
# Expected contents for Elysium (Ryzen 7 5800XT + RTX 3070 Ti, Samsung 970 EVO Plus NVMe):
#   - boot.kernelModules = ["kvm-amd"];
#   - boot.initrd.availableKernelModules includes "nvme"
#   - hardware.cpu.amd.updateMicrocode (auto-set by nixos-generate-config)
#   - real filesystem UUIDs for / and /boot
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0000-0000";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
